import { View, Text, StyleSheet, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { palette, riskColor } from '@/constants/colors';
import { MascotAssistant } from './MascotAssistant';
import { AnalysisResult } from '@/lib/agentEngine';

interface SafetyReportCardProps {
  result: AnalysisResult;
}

// Screenshot-worthy safety report card — the shareable artifact.
export function SafetyReportCard({ result }: SafetyReportCardProps) {
  const color = riskColor[result.riskLevel];
  const avgConf = Math.round(result.agents.reduce((s, a) => s + a.confidence, 0) / result.agents.length);
  const nextBreak = result.breakSchedule[0]?.activity ?? 'Hydration break';

  const rows: { label: string; value: string }[] = [
    { label: 'Location', value: result.weather.locationName },
    { label: 'Conditions', value: `${result.weather.tempC}°C · UV ${result.weather.uvIndex} · ${result.weather.humidity}% RH` },
    { label: 'Work type', value: result.workTypeLabel },
    { label: 'Worker action', value: result.workerAlerts[0]?.text.split('.')[0] ?? 'Hydrate and take shade breaks' },
    { label: 'Supervisor action', value: result.supervisorAction },
    { label: 'Next break', value: nextBreak },
    { label: 'Agent confidence', value: `${avgConf}% avg` },
  ];

  return (
    <View style={styles.card}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.brandRow}>
          <MascotAssistant size={44} glow={false} />
          <View>
            <Text style={styles.brand}>STARKZ AI</Text>
            <Text style={styles.sub}>Safety Report</Text>
          </View>
        </View>
        <Text style={styles.date}>{result.generatedAtLabel}</Text>
      </View>

      {/* Risk banner */}
      <View style={[styles.banner, { backgroundColor: `${color}1A`, borderColor: `${color}55` }]}>
        <View>
          <Text style={styles.bannerLabel}>RISK LEVEL</Text>
          <Text style={[styles.bannerLevel, { color }]}>{result.riskLevel}</Text>
        </View>
        <View style={[styles.scoreBubble, { borderColor: color }]}>
          <Text style={[styles.scoreNum, { color }]}>{result.riskScore}</Text>
        </View>
      </View>

      {/* Rows */}
      <View style={styles.rows}>
        {rows.map((r) => (
          <View key={r.label} style={styles.row}>
            <Text style={styles.rowLabel}>{r.label}</Text>
            <Text style={styles.rowValue} numberOfLines={3}>{r.value}</Text>
          </View>
        ))}
      </View>

      {/* Signature */}
      <View style={styles.signature}>
        <Ionicons name="shield-checkmark" size={13} color={palette.primary} />
        <Text style={styles.sigText}>
          Generated by Starkz AI{result.poweredByGroq ? ' · Groq reasoning' : ''}
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  card: {
    backgroundColor: palette.bgRaised,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    borderRadius: 24,
    padding: 18,
    ...Platform.select({
      web: { boxShadow: '0 20px 50px rgba(0,0,0,0.5)' } as any,
      default: { shadowColor: '#000', shadowOpacity: 0.5, shadowRadius: 30, shadowOffset: { width: 0, height: 16 }, elevation: 12 },
    }),
  },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  brand: { color: palette.text, fontSize: 16, fontWeight: '900', letterSpacing: 1.5, fontFamily: 'Inter_700Bold' },
  sub: { color: palette.textMuted, fontSize: 12, fontFamily: 'Inter_400Regular' },
  date: { color: palette.textFaint, fontSize: 11, fontFamily: 'Inter_400Regular', textAlign: 'right', maxWidth: 110 },
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  bannerLabel: { color: palette.textMuted, fontSize: 11, fontWeight: '700', letterSpacing: 1, fontFamily: 'Inter_600SemiBold' },
  bannerLevel: { fontSize: 26, fontWeight: '900', fontFamily: 'Inter_700Bold', marginTop: 2 },
  scoreBubble: { width: 56, height: 56, borderRadius: 28, borderWidth: 3, alignItems: 'center', justifyContent: 'center' },
  scoreNum: { fontSize: 22, fontWeight: '900', fontFamily: 'Inter_700Bold' },
  rows: { gap: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', gap: 16 },
  rowLabel: { color: palette.textFaint, fontSize: 12.5, fontFamily: 'Inter_500Medium', width: 110 },
  rowValue: { flex: 1, color: palette.text, fontSize: 12.5, lineHeight: 18, textAlign: 'right', fontFamily: 'Inter_500Medium' },
  signature: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: palette.border,
  },
  sigText: { color: palette.textMuted, fontSize: 11, fontFamily: 'Inter_400Regular' },
});
