/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/workTypes`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/weatherService`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/heatRiskEngine`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/groqService`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/agentEngine`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GlassPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MascotAssistant`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RiskGauge`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AgentRunCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WeatherEvidenceCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorkerAlertCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SafetyReportCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MetricBar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/loading`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/workTypes`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/weatherService`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/heatRiskEngine`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/groqService`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/agentEngine`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/GlassPanel`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/MascotAssistant`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/RiskGauge`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/AgentRunCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WeatherEvidenceCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WorkerAlertCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/SafetyReportCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/MetricBar`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/loading${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/scan${`?${string}` | `#${string}` | ''}` | `/../constants/workTypes${`?${string}` | `#${string}` | ''}` | `/../lib/weatherService${`?${string}` | `#${string}` | ''}` | `/../lib/heatRiskEngine${`?${string}` | `#${string}` | ''}` | `/../lib/groqService${`?${string}` | `#${string}` | ''}` | `/../lib/agentEngine${`?${string}` | `#${string}` | ''}` | `/../components/GlassPanel${`?${string}` | `#${string}` | ''}` | `/../components/MascotAssistant${`?${string}` | `#${string}` | ''}` | `/../components/RiskGauge${`?${string}` | `#${string}` | ''}` | `/../components/AgentRunCard${`?${string}` | `#${string}` | ''}` | `/../components/WeatherEvidenceCard${`?${string}` | `#${string}` | ''}` | `/../components/WorkerAlertCard${`?${string}` | `#${string}` | ''}` | `/../components/SafetyReportCard${`?${string}` | `#${string}` | ''}` | `/../components/MetricBar${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/workTypes`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/weatherService`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/heatRiskEngine`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/groqService`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/agentEngine`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GlassPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MascotAssistant`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RiskGauge`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AgentRunCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WeatherEvidenceCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorkerAlertCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SafetyReportCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MetricBar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
