/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/alert`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/report`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AgentRunCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GlassPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MascotAssistant`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MetricBar`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RiskGauge`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SafetyReportCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WeatherEvidenceCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorkTypePill`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorkerAlertCard`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../context/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/scan`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/alert`; params?: Router.UnknownOutputParams; } | { pathname: `/loading`; params?: Router.UnknownOutputParams; } | { pathname: `/report`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/AgentRunCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/GlassPanel`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/MascotAssistant`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/MetricBar`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/RiskGauge`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/SafetyReportCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WeatherEvidenceCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WorkTypePill`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/WorkerAlertCard`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/scan${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/alert${`?${string}` | `#${string}` | ''}` | `/loading${`?${string}` | `#${string}` | ''}` | `/report${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/../components/AgentRunCard${`?${string}` | `#${string}` | ''}` | `/../components/GlassPanel${`?${string}` | `#${string}` | ''}` | `/../components/MascotAssistant${`?${string}` | `#${string}` | ''}` | `/../components/MetricBar${`?${string}` | `#${string}` | ''}` | `/../components/RiskGauge${`?${string}` | `#${string}` | ''}` | `/../components/SafetyReportCard${`?${string}` | `#${string}` | ''}` | `/../components/WeatherEvidenceCard${`?${string}` | `#${string}` | ''}` | `/../components/WorkTypePill${`?${string}` | `#${string}` | ''}` | `/../components/WorkerAlertCard${`?${string}` | `#${string}` | ''}` | `/../constants/colors${`?${string}` | `#${string}` | ''}` | `/../context/ThemeContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/scan`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/alert`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/report`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/../components/AgentRunCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/GlassPanel`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MascotAssistant`; params?: Router.UnknownInputParams; } | { pathname: `/../components/MetricBar`; params?: Router.UnknownInputParams; } | { pathname: `/../components/RiskGauge`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SafetyReportCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WeatherEvidenceCard`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorkTypePill`; params?: Router.UnknownInputParams; } | { pathname: `/../components/WorkerAlertCard`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../context/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
